### PR TITLE
Only allocate real-space arrays when output is requested.

### LINKED ISSUE #654: Overflow Error
**Describe the bug**
Code crashes when trying to run larger problem.  This does not happen on Cole's branch.  I suspect this is because we're getting close to the 32 bit integer limit.  

**To Reproduce**
1. Run on current develop
2. `./asgard -p riemann_1x3v -d 3 -l "7 6 6 6" --mixed_grid_group 1 -x -t 2.3419e-4 -n 4 --wave_freq 1 --tol 1.0e-8 --kron-mode sparse --inner_it 50 -m 7'

**System:**
 - andremarie

**Additional context**
Debug output: 
```
asgard: /home/7r9/develop/asgard/src/asgard_vector.hpp:513: asgard::fk::vector<P, mem, resrc>::vector(int) [with asgard::mem_type m_ = asgard::mem_type::owner; <template-parameter-2-2> = void; P = double; asgard::mem_type mem = asgard::mem_type::owner; asgard::resource resrc = asgard::resource::host]: Assertion `size >= 0' failed.
```

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

The size of real-space arrays may be larger than INT_MAX, causing an assertion error. Since these arrays are for an optional output, when it isn't needed we can just set their size to zero.

I also promoted the variable in dense_space_size to int64_t and check its size before returning.

This fixes #654 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -144,7 +144,12 @@ int main(int argc, char **argv)
 
   // realspace solution vector - WARNING this is
   // currently infeasible to form for large problems
-  auto dense_size = asgard::dense_space_size(*pde);
+  int dense_size = 0;
+  if (cli_input.get_realspace_output_freq() > 0)
+  {
+    asgard::dense_space_size(*pde);
```
Comment (mkstoyanov) [inline src/main.cpp]:
```
  dense_size = asgard::dense_space_size(*pde);
```

Comment (quantumsteve) [reply src/main.cpp]: :facepalm:

**Review by mkstoyanov — APPROVED** [review]

**Review by stefan-schnake — APPROVED** [review]
We should consider removing the real_space features.  It's not reasonable that you would want full phase space data.  Maybe when the PDE rewrite is finished we could turn this into functionally that plots certain moments.
