### PR TITLE
Remove omp pragma simd with clang

### LINKED ISSUE #540: Kronmult ~7.5x slower with clang 14 vs gcc 11
**Describe the bug**
GCC 11.3.0
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.533 seconds.
single precision: 182.8424 Gflops / second.
double precision: 156.1806 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=10 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.548 seconds.
single precision: 101.7122 Gflops / second.
double precision: 83.2466 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=5 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.534 seconds.
single precision: 54.3392 Gflops / second.
double precision: 44.9719 Gflops / second.
```
clang 14.0.0
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.44 seconds.
single precision: 19.8238 Gflops / second.
double precision: 19.0290 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=10 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.502 seconds.
single precision: 10.0840 Gflops / second.
double precision: 9.9676 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=5 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 29.492 seconds.
single precision: 5.5760 Gflops / second.
double precision: 5.4787 Gflops / second.
```
**To Reproduce**
1. git commit hash being built
`5a1e28943391f1b828f78663440f39064aaff76f`
2. cmake command
`cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DASGARD_RECOMMENDED_DEFAULTS=ON ../`
3. full program/test invocation command
`OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000`
4. additional steps 
**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
 office workstation, ubuntu 22.04
 - modules loaded [e.g. output of `module list`]
  - other systems where this is reproducible [e.g. "my laptop", "none"]
 Similar issues on my laptop with an Ubuntu 23.04 container (gcc 12, clang 16)

**Additional context**

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Work around clang only partially implementing `#pragma omp simd`

This fixes #540 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by mkstoyanov** [comment]
Good job dealing with the strings and macros.

How much faster did it run on clang?

**Comment by quantumsteve** [comment]
Within the margin of error

this branch
```
$ ./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 4.42991 seconds.
double precision: 68.4510 Gflops / second.
```
develop
```
$ ./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 4.11911 seconds.
double precision: 69.3367 Gflops / second.
```

**Comment by quantumsteve** [comment]
Within the margin of error.

this branch
```
$ ./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 4.12667 seconds.
double precision: 76.6254 Gflops / second.
```

develop
```
$ ./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 4.13011 seconds.
double precision: 77.8342 Gflops / second.
```

**Comment by mkstoyanov** [comment]
I'll double check the benchmark as it may be affected by the bug in #562

**Comment by mkstoyanov** [comment]
Either you got hit with the bug (most likely) or the flags were off somewhere (less likely).

```
miz@tasmain:~/RAM/asgard $ ./asgard_kronmult_benchmark 3 2 688  3 36864
benchmarking:
dimensions: 3  n: 2  num_rows: 688  num_terms: 3  num_matrices: 36864
benchmark setup time: 0.367594 seconds.
double precision: 17.8337 Gflops / second.
./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 10.7452 seconds.
double precision: 15.4007 Gflops / second.
```

```
./asgard_kronmult_benchmark 3 2 688  3 36864
benchmarking:
dimensions: 3  n: 2  num_rows: 688  num_terms: 3  num_matrices: 36864
benchmark setup time: 0.358059 seconds.
double precision: 84.3462 Gflops / second.
./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 10.757 seconds.
double precision: 43.7185 Gflops / second.
```

For reference, when it comes to GCC, I get:
```
./asgard_kronmult_benchmark 3 2 688  3 36864
benchmarking:
dimensions: 3  n: 2  num_rows: 688  num_terms: 3  num_matrices: 36864
benchmark setup time: 0.0791751 seconds.
double precision: 246.8799 Gflops / second.
./asgard_kronmult_benchmark 3 2 4096 3 589824
benchmarking:
dimensions: 3  n: 2  num_rows: 4096  num_terms: 3  num_matrices: 589824
benchmark setup time: 2.74976 seconds.
double precision: 561.2081 Gflops / second.
```

It's amazing how much difference SIMD can make.

File: src/device/asgard_kronmult_common.hpp [hunk 1]
```diff
@@ -15,6 +15,15 @@
 
 #endif
 
+// As of LLVM version 16, clang does not utlize #pragma omp simd, resulting in a
+// pessimization
+#if defined(__clang__)
+#define PRAGMA_OMP_SIMD(x)
```
Comment (mkstoyanov) [inline src/device/asgard_kronmult_common.hpp]: Is it too much to have these prefixed by `ASGARD_` or `ASG_`.

Since this ends up being a public header, we should be careful about names. Alternatively, we can make a private header that is separate.

File: src/device/asgard_kronmult_common.hpp [hunk 2]
```diff
@@ -15,6 +15,15 @@
 
 #endif
 
+// As of LLVM version 16, clang does not utlize #pragma omp simd, resulting in a
+// pessimization
+#if defined(__clang__)
+#define ASGARD_PRAGMA_OMP_SIMD(x)
+#else
+#define PRAGMA(x) _Pragma(#x)
```
Comment (mkstoyanov) [inline src/device/asgard_kronmult_common.hpp]: Find-and-replace missed one.

**Review by mkstoyanov — APPROVED** [review]
