### PR TITLE
change memory_limit to avoid conflict

### LINKED ISSUE #509: Memory option conflicts with max level option
**Describe the bug**
The `--memory` [option's short version](https://github.com/project-asgard/asgard/blob/f977bd5c8fc1366f4d898c3c26db22fe352c6822/src/program_options.cpp#L68-L70) `-m` conflicts with the already existing `--max_level` / `-m` [option here](https://github.com/project-asgard/asgard/blob/f977bd5c8fc1366f4d898c3c26db22fe352c6822/src/program_options.cpp#L39-L41).

**To Reproduce**
Running asgard using `-m` intended for memory limit, i.e, `./asgard -p two_stream -d 3 -l "5 5" -f -x -t 6.25e-3 -m 4096` causes an error since it is interpreted as `max_level`:
```
The diagonal element of the triangular factor of A,
U(1,1) is zero, so that A is singular;
the solution could not be computed.
```

**Expected behavior**
We should either remove or rename the short version of `--memory` to something else. Running the above example with `--memory` instead works fine as intended, so this is not high priority.

**System:**
all

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Changes memory_limit option `-m` to `-mem` to avoid a conflict with max_level.

Fixes #509 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

File: src/program_options.cpp [hunk 1]
```diff
@@ -65,7 +65,7 @@ parser::parser(int argc, char const *const *argv)
       clara::detail::Opt(use_imex_stepping)["-x"]["--imex"](
           "Use IMEX (implicit-explicit) time advance (vs. explicit or "
           "implicit)") |
-      clara::detail::Opt(memory_limit, "size > 0")["-m"]["--memory"](
+      clara::detail::Opt(memory_limit, "size > 0")["-mem"]["--memory"](
```
Comment (ckendrick) [inline src/program_options.cpp]: I'm not sure if clara supports a short option with more than one character?
`./asgard -p two_stream -d 3 -l "5 5" -f -x -t 6.25e-3 -mem 4096`
```
Error in command line parsing: Expected argument following -m
invalid cli string; exiting
```

**Review by ckendrick — APPROVED** [review]
