### PR TITLE
Fix macOS Errors by using the cblas interface and clapack headers.

### LINKED ISSUE #399: macOS local test run failures.
**Describe the bug**
Running asgard tests locally on a macOS system results in several unit testing fails.

The following tests FAILED:
	  1 - adapt-test-mpi (Failed)
	  2 - adapt-test (Failed)
	  3 - basis-test (Failed)
	  5 - boundary_conditions-test (Failed)
	  6 - coefficients-test (Failed)
	 10 - fast_math-test (Failed)
	 11 - kronmult-test (Failed)
	 12 - lib_dispatch-test (Failed)
	 14 - pde-test (Failed)
	 17 - quadrature-test (Failed)
	 18 - solver-test (Failed)
	 19 - tensors-test (Failed)
	 20 - time_advance-test-mpi (Failed)
	 21 - time_advance-test (Failed)
	 23 - transformations-test (Failed)

**To Reproduce**

Note: this requires the pr https://github.com/project-asgard/asgard/pull/398

1. git commit hash being built
 35e54f54c32c97f9bbd8f5194f96c1bef5a6daf8

2. cmake command
`ccmake ../`
```
 ASGARD_BLAS_PATH                 OFF                                                                                                                                                                                                                                           
 ASGARD_BUILD_HDF5                OFF                                                                                                                                                                                                                                           
 ASGARD_BUILD_OPENBLAS            OFF                                                                                                                                                                                                                                           
 ASGARD_BUILD_PROFILE_DEPS        OFF                                                                                                                                                                                                                                           
 ASGARD_BUILD_TESTS               ON                                                                                                                                                                                                                                            
 ASGARD_GRAPHVIZ_PATH             OFF                                                                                                                                                                                                                                           
 ASGARD_HDF5_PATH                 OFF                                                                                                                                                                                                                                           
 ASGARD_IO_HIGHFIVE               OFF                                                                                                                                                                                                                                           
 ASGARD_LAPACK_PATH               OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_GPERF_CPU         OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_GPERF_MEM         OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_GPROF             OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_PERF              OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_VALGRIND          OFF                                                                                                                                                                                                                                           
 ASGARD_PROFILE_XRAY              OFF                                                                                                                                                                                                                                           
 ASGARD_TESTING_RANKS             0                                                                                                                                                                                                                                             
 ASGARD_USE_CUDA                  OFF                                                                                                                                                                                                                                           
 ASGARD_USE_DOUBLE_PREC           ON                                                                                                                                                                                                                                            
 ASGARD_USE_MATLAB                OFF                                                                                                                                                                                                                                           
 ASGARD_USE_MPI                   ON                                                                                                                                                                                                                                            
 ASGARD_USE_OPENMP                OFF                                                                                                                                                                                                                                           
 ASGARD_USE_SLATE                 OFF                                                                                                                                                                                                                                           
 BUILD_REPO_KRONMULT              https://github.com/project-asgard/kronmult.git                                                                                                                                                                                                
 BUILD_TAG_KRONMULT               431cc12                                                                                                                                                                                                                                       
 CMAKE_BUILD_TYPE                 Debug                                                                                                                                                                                                                                         
 CMAKE_EXECUTABLE_FORMAT          MACHO                                                                                                                                                                                                                                         
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                                                                                                                                                                    
 CMAKE_OSX_ARCHITECTURES                                                                                                                                                                                                                                                        
 CMAKE_OSX_DEPLOYMENT_TARGET      11.2                                                                                                                                                                                                                                          
 CMAKE_OSX_SYSROOT                /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk                                                                                                                                            
 FETCHCONTENT_BASE_DIR            ~/Projects/asgard/build/_deps                                                                                                                                                                                                        
 FETCHCONTENT_FULLY_DISCONNECTE   OFF                                                                                                                                                                                                                                           
 FETCHCONTENT_QUIET               ON                                                                                                                                                                                                                                            
 FETCHCONTENT_SOURCE_DIR_KRONMU                                                                                                                                                                                                                                                 
 FETCHCONTENT_UPDATES_DISCONNEC   OFF                                                                                                                                                                                                                                           
 FETCHCONTENT_UPDATES_DISCONNEC   OFF                                                                                                                                                                                                                                           
 USE_GPU                          OFF                
```

3. full program/test invocation command
```
make
make test
```

4. additional steps 

**Expected behavior**
Expected tests to pass.

**System:**
 - system name My iMac and PowerBook
 - modules loaded [e.g. output of `module list`] n/a
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

##### adapt-test-mpi
```
1/29 Testing: adapt-test-mpi
1/29 Test: adapt-test-mpi
Command: "/usr/local/bin/mpirun" "-n" "4" "./adapt-tests"
Directory: ~/Projects/asgard/build
"adapt-test-mpi" start time: Jul 13 12:27 EDT
Output:
----------------------------------------------------------
<snip> Lots of unrelated openmpi warnings.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
adapt-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
initial - diffusion 2d - float
-------------------------------------------------------------------------------
~/Projects/asgard/src/adapt_tests.cpp:250
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000146969380854

adapt-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
initial - diffusion 2d - float
-------------------------------------------------------------------------------
~/Projects/asgard/src/adapt_tests.cpp:250
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000146969380854

===============================================================================
All tests passed (1000 assertions in 10 test cases)

===============================================================================
===============================================================================
All tests passed (1000 assertions in 10 test cases)

===============================================================================
test cases:   10 |   9 passed | 1 failed
assertions: 1000 | 999 passed | 1 failed

test cases:   10 |   9 passed | 1 failed
assertions: 1000 | 999 passed | 1 failed

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56709,1],2]
  Exit code:    1
--------------------------------------------------------------------------
<end of output>
Test time =   4.26 sec
----------------------------------------------------------
Test Failed.
"adapt-test-mpi" end time: Jul 13 12:27 EDT
"adapt-test-mpi" time elapsed: 00:00:04
----------------------------------------------------------
```

##### adapt-test
```
2/29 Testing: adapt-test
2/29 Test: adapt-test
Command: "~/Projects/asgard/build/adapt-tests"
Directory: ~/Projects/asgard/build
"adapt-test" start time: Jul 13 12:27 EDT
Output:
----------------------------------------------------------
<snip> Lots of unrelated openmpi warnings.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
adapt-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
initial - diffusion 1d - float
-------------------------------------------------------------------------------
~/Projects/asgard/src/adapt_tests.cpp:221
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000019999999495

===============================================================================
test cases:   10 |    9 passed | 1 failed
assertions: 1002 | 1001 passed | 1 failed

<end of output>
Test time =   0.91 sec
----------------------------------------------------------
Test Failed.
"adapt-test" end time: Jul 13 12:27 EDT
"adapt-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### basis-test
```
3/29 Testing: basis-test
3/29 Test: basis-test
Command: "~/Projects/asgard/build/basis-tests"
Directory: ~/Projects/asgard/build
"basis-test" start time: Jul 13 12:27 EDT
Output:
----------------------------------------------------------
<snip> Lots of unrelated openmpi warnings.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
basis-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
Multiwavelet - float
  Multiwavelet generation, degree = 1
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:83
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893483749372592128.0f < 0.0001414214

-------------------------------------------------------------------------------
Multiwavelet - float
  Multiwavelet generation, degree = 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:89
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.0002

-------------------------------------------------------------------------------
Multiwavelet - float
  Multiwavelet generation, degree = 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:101
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.0004

-------------------------------------------------------------------------------
wavelet constructor - float, resource::host
  level 2 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:208
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.001

-------------------------------------------------------------------------------
wavelet constructor - float, resource::host
  level 5 degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:214
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.0005656854

-------------------------------------------------------------------------------
wavelet constructor - float, resource::host
  level 5 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:220
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.0028284271

-------------------------------------------------------------------------------
wavelet constructor - float, resource::device
  level 2 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:208
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.001

-------------------------------------------------------------------------------
wavelet constructor - float, resource::device
  level 5 degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:214
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.0005656854

-------------------------------------------------------------------------------
wavelet constructor - float, resource::device
  level 5 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:220
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.0028284271

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 2 degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:374
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.75449f < 0.000079999997979

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 2 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:381
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  15679456925039198208.0f < 0.00004472135842

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 5 degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:388
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.603620648384094f < 0.000119999996969

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 5 degree 6
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:395
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  11904309039837741056.0f
  <
  0.000239999993937

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 8 degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:403
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  13937120222130470912.0f < 0.00003999999899

-------------------------------------------------------------------------------
wavelet transform - float, resource::host
  level 8 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:410
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.613318562507629f < 0.000399999989895

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 2 degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:374
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  15178606288843046912.0f
  <
  0.000079999997979

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 2 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:381
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  11772328062086021120.0f
  <
  0.000199999994948

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 5 degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:388
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.633823454380035f < 0.000119999996969

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 5 degree 6
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:395
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.629967033863068f < 0.000239999993937

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 8 degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:403
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.527983367443085f < 0.000319999991916

-------------------------------------------------------------------------------
wavelet transform - float, resource::device
  level 8 degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/basis_tests.cpp:410
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.634805381298065f < 0.000199999994948

===============================================================================
test cases:  11 |   6 passed |  5 failed
assertions: 559 | 538 passed | 21 failed

<end of output>
Test time =  10.08 sec
----------------------------------------------------------
Test Failed.
"basis-test" end time: Jul 13 12:27 EDT
"basis-test" time elapsed: 00:00:10
----------------------------------------------------------
```

##### boundary_conditions-test
```
5/29 Testing: boundary_conditions-test
5/29 Test: boundary_conditions-test
Command: "~/Projects/asgard/build/boundary_conditions-tests"
Directory: ~/Projects/asgard/build
"boundary_conditions-test" start time: Jul 13 12:27 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
boundary_conditions-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
compute_boundary_conditions - float
  diffusion_1 level 2 degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/boundary_conditions_tests.cpp:249
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  10650764629103345664.0f
  <
  0.000002828427118

-------------------------------------------------------------------------------
compute_boundary_conditions - float
  diffusion_1 level 4 degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/boundary_conditions_tests.cpp:258
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  3486281441573076992.0f < 0.00000799999998

===============================================================================
test cases:  6 |  5 passed | 1 failed
assertions: 96 | 94 passed | 2 failed

<end of output>
Test time =   2.95 sec
----------------------------------------------------------
Test Failed.
"boundary_conditions-test" end time: Jul 13 12:27 EDT
"boundary_conditions-test" time elapsed: 00:00:02
----------------------------------------------------------
```

##### coefficients-test
```
6/29 Testing: coefficients-test
6/29 Test: coefficients-test
Command: "~/Projects/asgard/build/coefficients-tests"
Directory: ~/Projects/asgard/build
"coefficients-test" start time: Jul 13 12:27 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coefficients-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
diffusion 2 (single term) - float
  non-uniform level: levels 2, 3, degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:63
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.0019999999

-------------------------------------------------------------------------------
continuity 2 terms - float
  level 4, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:112
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.000048

-------------------------------------------------------------------------------
continuity 3 terms - float
  level 4, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:136
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.00064

-------------------------------------------------------------------------------
continuity 3 terms - float
  non uniform level: levels 2, 3, 2, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:144
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.00032

-------------------------------------------------------------------------------
continuity 6 terms - float
  level 2, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:160
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  4403503387312652288.0f < 0.00016

-------------------------------------------------------------------------------
continuity 6 terms - float
  non uniform level: levels 2, 3, 3, 3, 2, 4, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:168
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.00032

-------------------------------------------------------------------------------
fokkerplanck1_pitch_E case1 terms - float
  level 4, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:186
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.03397f < 0.00048

-------------------------------------------------------------------------------
fokkerplanck1_pitch_E case2 terms - float
  level 4, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:204
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.03397f < 0.00048

-------------------------------------------------------------------------------
fokkerplanck1_4p4 terms - float
  level 5, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:256
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.00419f < 0.000096

-------------------------------------------------------------------------------
fokkerplanck1_4p5 terms - float
  level 3, degree 5
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:273
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  370788821630976000.0f < 0.0039999999

-------------------------------------------------------------------------------
fokkerplanck2_complete terms - float
  level 3, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:292
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.0240000011

-------------------------------------------------------------------------------
fokkerplanck2_complete terms - float
  level 4, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:300
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.064000003

-------------------------------------------------------------------------------
fokkerplanck2_complete terms - float
  non-uniform levels: 2, 3, deg 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:307
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2.0f < 0.0120000006

-------------------------------------------------------------------------------
fokkerplanck2_complete terms - float
  non-uniform levels: 4, 2, deg 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/coefficients_tests.cpp:315
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.064000003

===============================================================================
test cases:  26 |  17 passed |  9 failed
assertions: 230 | 216 passed | 14 failed

<end of output>
Test time =  34.01 sec
----------------------------------------------------------
Test Failed.
"coefficients-test" end time: Jul 13 12:28 EDT
"coefficients-test" time elapsed: 00:00:34
----------------------------------------------------------
```

##### fast_math-test
```
9/29 Testing: elements-test
9/29 Test: elements-test
Command: "~/Projects/asgard/build/elements-tests"
Directory: ~/Projects/asgard/build
"elements-test" start time: Jul 13 12:28 EDT
Output:
----------------------------------------------------------
===============================================================================
All tests passed (4805 assertions in 3 test cases)

<end of output>
Test time =   0.50 sec
----------------------------------------------------------
Test Passed.
"elements-test" end time: Jul 13 12:28 EDT
"elements-test" time elapsed: 00:00:00
----------------------------------------------------------

10/29 Testing: fast_math-test
10/29 Test: fast_math-test
Command: "~/Projects/asgard/build/fast_math-tests"
Directory: ~/Projects/asgard/build
"fast_math-test" start time: Jul 13 12:28 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fast_math-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: owner, host
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:16
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: owner, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:23
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: const view, host
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:33
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: const view, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:43
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: view, host
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:56
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::vector: view, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:65
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::matrix: owner, host
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:88
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

-------------------------------------------------------------------------------
floating point norms - float
  fk::matrix: owner, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/fast_math_tests.cpp:95
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:132: FAILED:
  REQUIRE_THAT( first, Catch::Matchers::WithinAbs(second, tol * scale_fac) )
with expansion:
  32.49615f is within 0.0000387384 of 0.0

===============================================================================
test cases:  14 |  13 passed | 1 failed
assertions: 204 | 196 passed | 8 failed

<end of output>
Test time =   0.18 sec
----------------------------------------------------------
Test Failed.
"fast_math-test" end time: Jul 13 12:28 EDT
"fast_math-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### kronmult-test
```
11/29 Testing: kronmult-test
11/29 Test: kronmult-test
Command: "~/Projects/asgard/build/kronmult-tests"
Directory: ~/Projects/asgard/build
"kronmult-test" start time: Jul 13 12:28 EDT
Output:
----------------------------------------------------------
<snip> Lots of unrelated openmpi warnings.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kronmult-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
test kronmult - float
  1d
-------------------------------------------------------------------------------
~/Projects/asgard/src/kronmult_tests.cpp:67
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  246650591600705536.0f < 0.0000005657

-------------------------------------------------------------------------------
test kronmult w/ decompose - float
  2d - uniform level
-------------------------------------------------------------------------------
~/Projects/asgard/src/kronmult_tests.cpp:122
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  6693250727411712.0f < 0.000010560000192

===============================================================================
test cases:  4 |  2 passed | 2 failed
assertions: 16 | 14 passed | 2 failed

<end of output>
Test time = 454.76 sec
----------------------------------------------------------
Test Failed.
"kronmult-test" end time: Jul 13 12:36 EDT
"kronmult-test" time elapsed: 00:07:34
----------------------------------------------------------
```

##### lib_dispatch-test
```
12/29 Testing: lib_dispatch-test
12/29 Test: lib_dispatch-test
Command: "~/Projects/asgard/build/lib_dispatch-tests"
Directory: ~/Projects/asgard/build
"lib_dispatch-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib_dispatch-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
dot product (lib_dispatch::dot) - float
  lib_dispatch::dot - inc = 1
-------------------------------------------------------------------------------
~/Projects/asgard/src/lib_dispatch_tests.cpp:740
...............................................................................

~/Projects/asgard/src/lib_dispatch_tests.cpp:745: FAILED:
  REQUIRE( ans == gold )
with expansion:
  0.0f == 110.0f

-------------------------------------------------------------------------------
dot product (lib_dispatch::dot) - float
  lib_dispatch::dot - inc = 1, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/lib_dispatch_tests.cpp:747
...............................................................................

~/Projects/asgard/src/lib_dispatch_tests.cpp:755: FAILED:
  REQUIRE( ans == gold )
with expansion:
  0.0f == 110.0f

-------------------------------------------------------------------------------
dot product (lib_dispatch::dot) - float
  lib_dispatch::dot - inc =/= 1
-------------------------------------------------------------------------------
~/Projects/asgard/src/lib_dispatch_tests.cpp:758
...............................................................................

~/Projects/asgard/src/lib_dispatch_tests.cpp:769: FAILED:
  REQUIRE( ans == gold )
with expansion:
  0.0f == 110.0f

-------------------------------------------------------------------------------
dot product (lib_dispatch::dot) - float
  lib_dispatch::dot - inc =/= 1, device
-------------------------------------------------------------------------------
~/Projects/asgard/src/lib_dispatch_tests.cpp:771
...............................................................................

~/Projects/asgard/src/lib_dispatch_tests.cpp:787: FAILED:
  REQUIRE( ans == gold )
with expansion:
  0.0f == 110.0f

===============================================================================
test cases:  27 |  26 passed | 1 failed
assertions: 224 | 220 passed | 4 failed

<end of output>
Test time =   0.37 sec
----------------------------------------------------------
Test Failed.
"lib_dispatch-test" end time: Jul 13 12:36 EDT
"lib_dispatch-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### pde-test
```
14/29 Testing: pde-test
14/29 Test: pde-test
Command: "~/Projects/asgard/build/pde-tests"
Directory: ~/Projects/asgard/build
"pde-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pde-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
testing diffusion 1 implementations - float
  diffusion 1 source functions
-------------------------------------------------------------------------------
~/Projects/asgard/src/pde_tests.cpp:119
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f < 0.00002236067921

-------------------------------------------------------------------------------
testing contuinity 6 implementations - float
  continuity 6 exact solution functions
-------------------------------------------------------------------------------
~/Projects/asgard/src/pde_tests.cpp:242
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f < 0.00002236067921

-------------------------------------------------------------------------------
testing contuinity 6 implementations - float
  continuity 6 source functions
-------------------------------------------------------------------------------
~/Projects/asgard/src/pde_tests.cpp:247
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f < 0.00002236067921

-------------------------------------------------------------------------------
testing fokkerplanck2_complete implementations - float
  fp2 complete initial condition functions
-------------------------------------------------------------------------------
~/Projects/asgard/src/pde_tests.cpp:273
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  35864943398146277376.0f < 0.00002236067921

===============================================================================
test cases:  14 |  11 passed | 3 failed
assertions: 194 | 190 passed | 4 failed

<end of output>
Test time =  12.41 sec
----------------------------------------------------------
Test Failed.
"pde-test" end time: Jul 13 12:36 EDT
"pde-test" time elapsed: 00:00:12
----------------------------------------------------------
```

##### quadrature-test
```
17/29 Testing: quadrature-test
17/29 Test: quadrature-test
Command: "~/Projects/asgard/build/quadrature-tests"
Directory: ~/Projects/asgard/build
"quadrature-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quadrature-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
legendre/legendre derivative function - float
  legendre(linspace (-2.5, 3.0, 11), 5)
-------------------------------------------------------------------------------
~/Projects/asgard/src/quadrature_tests.cpp:40
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  2812740684484706304.0f < 0.0000074162

===============================================================================
test cases:  4 |  3 passed | 1 failed
assertions: 20 | 19 passed | 1 failed

<end of output>
Test time =   0.19 sec
----------------------------------------------------------
Test Failed.
"quadrature-test" end time: Jul 13 12:36 EDT
"quadrature-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### solver-test
```
18/29 Testing: solver-test
18/29 Test: solver-test
Command: "~/Projects/asgard/build/solver-tests"
Directory: ~/Projects/asgard/build
"solver-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------
<end of output>
Test time =   0.18 sec
----------------------------------------------------------
Test Failed.
"solver-test" end time: Jul 13 12:36 EDT
"solver-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### tensors-test
```
19/29 Testing: tensors-test
19/29 Test: tensors-test
Command: "~/Projects/asgard/build/tensors-tests"
Directory: ~/Projects/asgard/build
"tensors-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensors-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
fk::vector operators - float
  vector*vector operator
-------------------------------------------------------------------------------
~/Projects/asgard/src/tensors_tests.cpp:589
...............................................................................

~/Projects/asgard/src/tensors_tests.cpp:597: FAILED:
  REQUIRE( (gold * gold) == inner_prod )
with expansion:
  0.0f == 90.0f

===============================================================================
test cases:   26 |   25 passed | 1 failed
assertions: 2217 | 2216 passed | 1 failed

<end of output>
Test time =   0.24 sec
----------------------------------------------------------
Test Failed.
"tensors-test" end time: Jul 13 12:36 EDT
"tensors-test" time elapsed: 00:00:00
----------------------------------------------------------
```

##### time_advance-test-mpi
```
20/29 Testing: time_advance-test-mpi
20/29 Test: time_advance-test-mpi
Command: "/usr/local/bin/mpirun" "-n" "4" "./time_advance-tests"
Directory: ~/Projects/asgard/build
"time_advance-test-mpi" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------
<snip> Lots of unrelated OpenMPI warnings.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
time_advance-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
time_advance-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
time_advance-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 2, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:99
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 2, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:99
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.00003999999899

with expansion:
  diffusion2, explicit, sparse grid, level 2, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:99
...............................................................................
  36893488147419103232.0f < 0.00003999999899


~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.00003999999899


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
time_advance-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 2, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:99
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f < 0.00003999999899

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 3, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:118
...............................................................................

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 3, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:118
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  2.0f < 0.000094868327408

  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000094868327408

[**:33517] *** An error occurred in MPI_Allreduce
[**:33517] *** reported by process [3720413185,0]
[**:33517] *** on communicator MPI COMMUNICATOR 5 SPLIT FROM 0
[**:33517] *** MPI_ERR_TRUNCATE: message truncated
[**:33517] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[**:33517] ***    and potentially your MPI job)
[**:33516] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
[**:33516] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[**:33516] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
<end of output>
Test time =  12.50 sec
----------------------------------------------------------
Test Failed.
"time_advance-test-mpi" end time: Jul 13 12:36 EDT
"time_advance-test-mpi" time elapsed: 00:00:12
----------------------------------------------------------
```

##### time_advance-test
```
21/29 Testing: time_advance-test
21/29 Test: time_advance-test
Command: "~/Projects/asgard/build/time_advance-tests"
Directory: ~/Projects/asgard/build
"time_advance-test" start time: Jul 13 12:36 EDT
Output:
----------------------------------------------------------
<Snip> Lots of unrelated OpenMPI warnings.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
time_advance-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 2, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:99
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000056568541066

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 3, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:118
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000134164075261

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit, sparse grid, level 4, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:136
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  2.771281333405513

-------------------------------------------------------------------------------
time advance - diffusion 2 - float
  diffusion2, explicit/non-uniform level, sparse grid, degree 2
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:153
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000195959174472

-------------------------------------------------------------------------------
time advance - diffusion 1 - float
  diffusion1, explicit, sparse grid, level 4, degree 4
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:311
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  1.999546647071838f < 0.079999998211861

-------------------------------------------------------------------------------
time advance - continuity 1 - float
  continuity1, explicit, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:341
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000000282842716

-------------------------------------------------------------------------------
time advance - continuity 1 - float
  continuity1, explicit, level 2, degree 2, full grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:356
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000000282842716

-------------------------------------------------------------------------------
time advance - continuity 1 - float
  continuity1, explicit, level 4, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:371
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000000692820331

-------------------------------------------------------------------------------
time advance - continuity 2 - float
  continuity2, explicit, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:396
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000000565685432

-------------------------------------------------------------------------------
time advance - continuity 2 - float
  continuity2, explicit, level 2, degree 2, full grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:411
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000000800000009

-------------------------------------------------------------------------------
time advance - continuity 2 - float
  continuity2, explicit, level 4, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:426
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000002078460993

-------------------------------------------------------------------------------
time advance - continuity 3 - float
  continuity3, explicit, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:466
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f < 0.00000010198039

-------------------------------------------------------------------------------
time advance - continuity 3 - float
  continuity3, explicit, level 4, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:481
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000000529905649

-------------------------------------------------------------------------------
time advance - continuity 3 - float
  continuity3, explicit/non-uniform level, degree 4, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:496
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000006974238391

-------------------------------------------------------------------------------
time advance - continuity 6 - float
  continuity6, level 2, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:524
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  1.015649557113647f < 0.000157435700763

-------------------------------------------------------------------------------
time advance - continuity 6 - float
  continuity6, explicit/non-uniform level, degree 4, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:539
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000089799777056

-------------------------------------------------------------------------------
time advance - fokkerplanck_1d_pitch_C - float
  fokkerplanck_1d_pitch_C, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:564
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  8695879134405984256.0f < 0.000002828427118

-------------------------------------------------------------------------------
time advance - fokkerplanck_1d_4p3 - float
  fokkerplanck_1d_4p3, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:587
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000002828427118

-------------------------------------------------------------------------------
time advance - fokkerplanck_1d_pitch_E_case1 - float
  fokkerplanck_1d_pitch_E_case1, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:616
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  1.414213538169861f < 0.000028284270533

-------------------------------------------------------------------------------
time advance - fokkerplanck_1d_pitch_E_case2 - float
  fokkerplanck_1d_pitch_E_case2, level 2, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:641
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000028284270533

-------------------------------------------------------------------------------
implicit time advance - fokkerplanck_2d_complete - float
  fokkerplanck_2d_complete, level 5, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:704
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000317490149307

-------------------------------------------------------------------------------
implicit time advance - fokkerplanck_2d_complete - float
  fokkerplanck_2d_complete, implicit/non-uniform level, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:724
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000119999996969

-------------------------------------------------------------------------------
implicit time advance - diffusion 2 - float
  diffusion2, implicit, sparse grid, level 3, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:781
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000134164075261

-------------------------------------------------------------------------------
implicit time advance - diffusion 2 - float
  diffusion2, implicit, sparse grid, level 4, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:796
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000207846091658

-------------------------------------------------------------------------------
implicit time advance - diffusion 2 - float
  diffusion2, implicit, sparse grid, level 5, degree 3
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:811
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000317490149307

-------------------------------------------------------------------------------
implicit time advance - diffusion 2 - float
  diffusion2, implicit/non-uniform level, degree 2, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:826
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  2.0f < 0.000195959174472

-------------------------------------------------------------------------------
implicit time advance - continuity 2 - float
  continuity2, level 4, degree 3, sparse grid
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:929
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000002078460993

-------------------------------------------------------------------------------
implicit time advance - continuity 2 - float
  continuity2, level 4, degree 3, sparse grid, iterative
-------------------------------------------------------------------------------
~/Projects/asgard/src/time_advance_tests.cpp:945
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:35: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  36893488147419103232.0f
  <
  0.000002078460993

===============================================================================
test cases:  30 |  17 passed | 13 failed
assertions: 318 | 290 passed | 28 failed

<end of output>
Test time = 441.89 sec
----------------------------------------------------------
Test Failed.
"time_advance-test" end time: Jul 13 12:43 EDT
"time_advance-test" time elapsed: 00:07:21
----------------------------------------------------------
```

##### transformations-test
```
23/29 Testing: transformations-test
23/29 Test: transformations-test
Command: "~/Projects/asgard/build/transformations-tests"
Directory: ~/Projects/asgard/build
"transformations-test" start time: Jul 13 12:44 EDT
Output:
----------------------------------------------------------

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
transformations-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
gen_realspace_transform - float
  gen_realspace_transform_2
-------------------------------------------------------------------------------
~/Projects/asgard/src/transformations_tests.cpp:301
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  0.128199338912964f < 0.076799998059869

-------------------------------------------------------------------------------
gen_realspace_transform - float
  gen_realspace_transform_6
-------------------------------------------------------------------------------
~/Projects/asgard/src/transformations_tests.cpp:330
...............................................................................

~/Projects/asgard/testing/tests_general.hpp:52: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(m0.size())) )
with expansion:
  36893488147419103232.0f < 0.00001199999997

===============================================================================
test cases:  8 |  7 passed | 1 failed
assertions: 96 | 94 passed | 2 failed

<end of output>
Test time =   6.76 sec
----------------------------------------------------------
Test Failed.
"transformations-test" end time: Jul 13 12:44 EDT
"transformations-test" time elapsed: 00:00:06
----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by cianciosa**
## Proposed changes
This fixes the test failures reported in https://github.com/project-asgard/asgard/issues/399 by switching to use the cblas interface.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

The builds fails on GitHub actions linux. It looks like it fails to find the clapack header. This may need to revery the non __APPLE__ branch to manual export for lapack libraries. 

## What systems has this change been tested on?
macOS

## Checklist

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by cianciosa** [comment]
This PR add a GitHub action. But that won't automatically run until after the is merged. There results of the test can be seen here

https://github.com/cianciosa/asgard/actions/runs/1060276930

**Comment by quantumsteve** [comment]
I don't think there is a standard C interface to the Fortran LAPACK
http://nicolas.limare.net/pro/notes/2014/10/31_cblas_clapack_lapacke/
http://math-atlas.sourceforge.net/faq.html#clapackStand

**Comment by cianciosa** [comment]
I looked in openblas source and saw it had a clapack and assumed it was standard with every lapack instance. It should be simple to revert that for non-apple builds.

On Jul 23, 2021, at 1:16 PM, Steven Hahn ***@***.******@***.***>> wrote:



I don't think there is a standard C interface to the Fortran LAPACK
http://nicolas.limare.net/pro/notes/2014/10/31_cblas_clapack_lapacke/
http://math-atlas.sourceforge.net/faq.html#clapackStand

**Comment by cianciosa** [comment]
The linux GitHub actions now builds and passes tests. https://github.com/cianciosa/asgard/runs/3145995499?check_suite_focus=true

File: src/lib_dispatch.hpp [hunk 1]
```diff
@@ -1,82 +1,15 @@
...
-enum class resource
-{
-  host,
-  device
-};
-
 // ==========================================================================
 // external declarations for calling blas routines linked with -lblas
 // ==========================================================================
+#ifdef __APPLE__
```
Comment (quantumsteve) [inline src/lib_dispatch.hpp]: Apple + Other BLAS libraries (OpenBLAS, MKL, etc.) should be acceptable combinations.

**Comment by quantumsteve** [comment]
Our AWS builds still have header issues.
```
/codebuild/output/src118884115/src/github.com/project-asgard/asgard/src/lib_dispatch.hpp:9:10: fatal error: cblas.h: No such file or directory
```
 May we use the same Docker container on AWS Codebuild and GitHub actions?

**Comment by cianciosa** [comment]
I think the asgard-unit-cuda-gxx test is failing because the lib_dispatch is compiled before OpenBlas is installed so it never picks up the cblas header.

File: .github/workflows/ci_tests.yaml [hunk 2]
```diff
@@ -0,0 +1,36 @@
+name: Continuous Integration Test
+on:
+    workflow_dispatch:
+    push:
+    pull_request:
+jobs:
+    ci_test:
+        strategy:
+            matrix:
+                os: [macos-latest, ubuntu-latest]
```
Comment (quantumsteve) [inline .github/workflows/ci_tests.yaml]: Adding a MacOS build here make sense (not available in AWS Codebuild), but the Linux tests duplicate what we already have on AWS.

File: CMakeLists.txt [hunk 3]
```diff
@@ -99,6 +99,8 @@ endif()
 ## Pull in external support as needed
 ###############################################################################
 
+set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}/contrib)
```
Comment (quantumsteve) [inline CMakeLists.txt]: I think the modern suggest is to use [`list(APPEND <list> [<element>...])`](https://cmake.org/cmake/help/latest/command/list.html#append)

```suggestion
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/contrib)
```

File: CMakeLists.txt [hunk 4]
```diff
@@ -287,7 +285,7 @@ if (ASGARD_USE_SLATE)
   target_link_libraries (lib_dispatch PRIVATE slate_lapack_api)
   target_compile_definitions (lib_dispatch PUBLIC ASGARD_USE_SLATE)
 else ()
-  target_link_libraries (lib_dispatch PRIVATE ${LINALG_LIBS})
+  target_link_libraries (lib_dispatch PUBLIC LINALG::LINALG)
```
Comment (quantumsteve) [inline CMakeLists.txt]: Why is this change necessary? It seems to build fine when I set this to private 😕

File: CMakeLists.txt [hunk 5]
```diff
@@ -434,7 +432,7 @@ if (ASGARD_BUILD_TESTS)
   add_executable (kronmult_cuda-tests src/device/kronmult_cuda_tests.cpp)
   target_include_directories (kronmult_cuda-tests PRIVATE ${CMAKE_SOURCE_DIR}/testing)
   target_include_directories (kronmult_cuda-tests PRIVATE ${CMAKE_BINARY_DIR})
-  target_link_libraries (kronmult_cuda-tests PRIVATE coefficients kronmult_cuda tests_general)
+  target_link_libraries (kronmult_cuda-tests PRIVATE coefficients kronmult_cuda tests_general LINALG::LINALG)
```
Comment (quantumsteve) [inline CMakeLists.txt]: Why do we need to start linking against `LINALG::LINALG` here?

File: contrib/FindLINALG.cmake [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+              SCSL
+              SGIMATH
+              SunPerf
+)
+
+#  Check for platform provided BLAS and LAPACK libaries. If these were not found
+#  then build the openblas library.
+if (NOT ${ASGARD_BUILD_OPENBLAS})
+    find_package (BLAS)
+    find_package (LAPACK)
```
Comment (quantumsteve) [inline contrib/FindLINALG.cmake:38]: Should we pass the `BLA_VENDOR` property to these two finders?

File: contrib/FindLINALG.cmake [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+              Fujitsu_SSL2 Fujitsu_SSL2BLAMP
+              Goto GotoBLAS
+              IBMESSL
+              Intel Intel10_32 Intel10_64lp Intel10_64lp_seq Intel10_64ilp Intel10_64ilp_seq Intel10_64_dyn
+              NVHPC
+              OpenBLAS
+              PhiPACK
+              SCSL
+              SGIMATH
+              SunPerf
```
Comment (quantumsteve) [inline contrib/FindLINALG.cmake]: Can we prune this list to better match what's currently being tested and likely to be used with ASGarD?

File: src/lib_dispatch.cpp [hunk 8]
```diff
@@ -506,14 +550,30 @@ void gemv(char const *trans, int *m, int *n, P *alpha, P *A, int *lda, P *x,
 #endif
   }
 
+  CBLAS_TRANSPOSE transpose;
```
Comment (quantumsteve) [inline src/lib_dispatch.cpp]: Since this pattern repeats 3 times, make it function.

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Overall this looks good. See comments for recommended changes.

File: contrib/FindLINALG.cmake (hunk 7 above)
Comment (cianciosa) [reply contrib/FindLINALG.cmake]: I've pruned out the ones that were obviously deprecated or obsolete platforms (mips, alpha, sparc, obscure Russian processor). I left in all the cases for current architectures (arm, x86, POWER9). However there are some that aren't clear what their status is.

- ATLAS (Not sure if this is still actively developed.)
- FLAME (Is under active develop at the UT-Austin supercomputer center)
- Fujitsu ones are for the current fastest super computer (Fugaku).
- SCSL Not sure but I think this is cray version.

File: src/lib_dispatch.cpp (hunk 8 above)
Comment (cianciosa) [reply src/lib_dispatch.cpp]: I have refactored it into a function. Right now the function checks for n,N,t,T and assumes anything else is a conjugate transpose. Should I explicitly check or c,C and assert on anything else instead?

File: CMakeLists.txt (hunk 3 above)
Comment (cianciosa) [reply CMakeLists.txt]: Fixed

File: CMakeLists.txt (hunk 4 above)
Comment (cianciosa) [reply CMakeLists.txt]: This was reverted back.

File: CMakeLists.txt (hunk 5 above)
Comment (cianciosa) [reply CMakeLists.txt]: This was reverted back also.

**Review by quantumsteve — APPROVED** [review]

File: src/lib_dispatch.cpp (hunk 8 above)
Comment (quantumsteve) [reply src/lib_dispatch.cpp]: I think fast-math creates the string so user input won't create an issue here.
